puts "📃 Seeding data..."

u1 = User.create(username: "francis", password: "1234567")
u2 = User.create(username: "charlie", password: "1234567")
u3 = User.create(username: "macario", password: "1234567")
u4 = User.create(username: "jacob", password: "1234567")
u5 = User.create(username: "leticia", password: "1234567")

Recipe.create(user_id: u1.id, title: "Pumpkin Pie", instructions: "Step 1 - Preheat the oven to 425 degrees F (220 degrees C). Step 2 - Combine eggs, pumpkin puree, sweetened condensed milk, and pumpkin pie spice in a large bowl and mix until combined. Step 3 - Fit pie crust into a 9-inch pie dish; pour pumpkin mixture into the crust. Step 4 - Place pie on a baking sheet and bake in the preheated oven for 15 minutes. Reduce heat to 350 degrees F (175 degrees C) and bake until filling is set, 35 to 40 minutes.", minutes_to_complete: 60)
Recipe.create(user_id: u2.id, title: "Italian Cheesecake", instructions: "Step 1 - Preheat oven to 400 degrees F (205 degrees C). Grease and flour one 9 inch round springform or regular pan. Step 2 - Combine the ricotta, confectioners' sugar and eggs. Blend well. Stir in vanilla, almond extract, rum extract, lemon juice, lemon zest and orange zest. Beat by hand until smooth and creamy. Pour batter into the prepared pan. Step 3 - Bake at 400 degrees F (205 degrees C) for 40 minutes, until golden. Place on a rack and cool.", minutes_to_complete: 90)
Recipe.create(user_id: u3.id, title: "Mom's Cheesecake", instructions: "Step 1 - Preheat oven to 350 degrees F (175 degrees C). In a medium bowl, combine graham cracker crumbs, 3 tablespoons sugar, cinnamon and melted margarine. Mix all ingredients well and press into bottom and sides of a 9 inch springform pan. Step 2 - In a large bowl, beat cream cheese and sugar until smooth. Blend in the eggs one at a time, then stir in the vanilla and salt. Fold in the sour cream. Step 3 - Pour batter into springform pan. Bake in preheated oven for 1 hour. Turn off oven and leave cake in for at least 30 minutes.", minutes_to_complete: 90)
Recipe.create(user_id: u4.id, title: "Autumn Cheesecake", instructions: "Step 1 - Preheat oven to 350 degrees F (175 degrees C). In a large bowl, stir together the graham cracker crumbs, 1/2 cup finely chopped pecans, 3 tablespoons sugar, 1/2 teaspoon cinnamon and melted butter; press into the bottom of a 9 inch springform pan. Bake in preheated oven for 10 minutes. Step 2 - In a large bowl, combine cream cheese and 1/2 cup sugar. Mix at medium speed until smooth. Beat in eggs one at a time, mixing well after each addition. Blend in vanilla; pour filling into the baked crust. Step 3 - In a small bowl, stir together 1/3 cup sugar and 1/2 teaspoon cinnamon. Toss the cinnamon-sugar with the apples to coat. Spoon apple mixture over cream cheese layer and sprinkle with 1/4 cup chopped pecans. Step 4 - Bake in preheated oven for 60 to 70 minutes. With a knife, loosen cake from rim of pan. Let cool, then remove the rim of pan. Chill cake before serving.", minutes_to_complete: 140)
Recipe.create(user_id: u5.id, title: "Persimmon Cheesecake", instructions: "Step 1 - Preheat oven to 325 degrees F (165 degrees C). Step 2 - Chop the walnuts in a food processor until fine. Mix together in a bowl with the brown sugar and melted butter. Press the mixture into the bottom of a 9-inch springform pan. Step 3 - Bake in the preheated oven for 12 minutes. Set aside to cool completely. Step 4 - Combine the persimmons, cream cheese, 1 1/4 cup sugar, 3/4 cup sour cream, cinnamon, and ginger in a food processor. Blend in processor until smooth, stopping occasionally to scrape edges of food processor bowl with a spatula. Add the eggs, one at a time, and process until fully incorporated. Pour the mixture over the cooled crust. Step 5 - Bake in the preheated oven until mostly set with the center being slightly jiggly, 60 to 75 minutes. Step 6 - While the cheesecake is baking, whisk together the 1 1/4 sour cream, 3 tablespoon white sugar, and vanilla extract. Spread evenly over the cheesecake while still hot and return to oven another 10 minutes. Allow to cool completely. Loosely cover with aluminum foil and refrigerate 4 to 8 hours or overnight before serving.", minutes_to_complete: 347)

puts "✅ Done seeding"